sudo: false
language: ruby
rvm:
  - 2.3.3
  - ruby-head
  - jruby-9.1.6.0
  - jruby-head
env:
  - sinatra=1.4.7 rails=4.2.7.1
  - sinatra=2.0.0.beta2 rails=5.0.0.1
jdk:
  - oraclejdk8
before_install:
  - gem uninstall bundler
  - gem install bundler -v 1.11.2
