sudo: false
language: ruby
rvm:
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-9.1.7.0
  - jruby-head
jdk:
  - oraclejdk8
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
